let rebateData;const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);const norm=s=>s.toUpperCase().replace(/[^A-Z0-9]/g,'');
fetch('rebate-data.json').then(r=>r.json()).then(d=>{rebateData=d;render([]);const saved=localStorage.getItem('applianceRebateModels');if(saved){modelsInput.value=saved;calculate()}});
const $=id=>document.getElementById(id);const modelsInput=$('modelsInput');$('calculateBtn').onclick=calculate;$('clearBtn').onclick=()=>{modelsInput.value='';localStorage.removeItem('applianceRebateModels');render([])};$('printBtn').onclick=()=>window.print();modelsInput.addEventListener('input',()=>{$('modelCount').textContent=parseModels().length+' models entered'});
function parseModels(){return modelsInput.value.split(/[\s,;]+/).map(norm).filter(Boolean)}
function lookup(program,model){return program.models.find(x=>x.model===model)}
function categoryIncludes(cat,words){return words.some(w=>cat.toLowerCase().includes(w.toLowerCase()))}
function calcCafe(models,p){let matches=models.map(m=>lookup(p,m));let counts=matches.map(Boolean);let categorySeen={};matches.forEach((x,i)=>{if(!x)return;let cat=x.category;let limited=categoryIncludes(cat,p.rules.singleCountCategoryKeywords);if(limited){if(categorySeen[cat])counts[i]=false;categorySeen[cat]=true}});let dishIdx=[];matches.forEach((x,i)=>{if(x&&x.category.toLowerCase().includes('dishwasher'))dishIdx.push(i)});dishIdx.slice(p.rules.dishwasherCap).forEach(i=>counts[i]=false);let count=counts.filter(Boolean).length;let base=p.tiers[String(Math.min(count,p.rules.maxBaseCount))]||0;if(count===2&&dishIdx.length>0&&p.rules.twoPieceDishwasherExclusion)base=0;let cats=matches.filter(Boolean).map(x=>x.category.toLowerCase());let wall=cats.some(c=>c.includes('wall oven'));let cook=cats.some(c=>c.includes('cooktop'));let range=cats.some(c=>c.includes('commercial-style range'));let bonus=(wall&&cook?p.rules.wallOvenCooktopBonus:0)+(range?p.rules.commercialStyleRangeBonus:0);return{count,amount:base+bonus,base,bonus,matches,counts,status:base+bonus?'Eligible':'Not eligible',extra:[wall&&cook?'Wall oven + cooktop bonus applied':null,range?'Commercial-style range bonus applied':null].filter(Boolean)}}
function calcProfile(models,p){let matches=models.map(m=>lookup(p,m));let counts=matches.map(Boolean),seen={};matches.forEach((x,i)=>{if(!x)return;let limited=categoryIncludes(x.category,p.rules.singleCountCategoryKeywords);if(limited){let key=categoryIncludes(x.category,['Microwave'])?'Microwave':'Ventilation';if(seen[key])counts[i]=false;seen[key]=true}});let count=counts.filter(Boolean).length;let amount=p.tiers[String(Math.min(count,p.rules.maxBaseCount))]||0;return{count,amount,matches,counts,status:amount?'Eligible':'Not eligible',extra:[]}}
function calcCommercial(models,p){let matches=models.map(m=>lookup(p,m));let ok=models.includes(p.rules.washer)&&p.rules.dryers.some(d=>models.includes(d));return{count:ok?2:matches.filter(Boolean).length,amount:ok?p.rules.payout:0,matches,counts:matches.map(Boolean),status:ok?'Eligible':'Needs qualifying pair',extra:[]}}
function calcMonogram(models,p){let matches=models.map(m=>lookup(p,m)),count=matches.filter(Boolean).length;return{count,amount:count?p.rules.payout:0,matches,counts:matches.map(Boolean),status:count?'Eligible':'Not eligible',extra:[]}}
function calculate(){let models=parseModels();localStorage.setItem('applianceRebateModels',models.join('\n'));render(models)}
function render(models){if(!rebateData)return;let results={};for(const p of rebateData.programs){results[p.id]=p.id==='cafe'?calcCafe(models,p):p.id==='profile'?calcProfile(models,p):p.id==='commercial'?calcCommercial(models,p):calcMonogram(models,p)}let total=Object.values(results).reduce((s,r)=>s+r.amount,0);$('totalSavings').textContent=money(total);$('modelCount').textContent=models.length+' models entered';$('summaryCards').innerHTML=rebateData.programs.map(p=>{let r=results[p.id];return `<article class="summary-card" style="--accent:${p.color}"><div class="top"><div><h4>${p.name}</h4><span class="sub">${p.validDates}</span></div><div class="amount">${money(r.amount)}</div></div><div class="metrics"><div class="metric"><strong>${r.count}</strong><span>ELIGIBLE / COUNTED</span></div><div class="metric"><strong>${r.status}</strong><span>STATUS</span></div></div>${r.extra.length?`<div class="pill yes">${r.extra.join(' • ')}</div>`:''}<ul>${p.notes.map(n=>`<li>${n}</li>`).join('')}</ul></article>`}).join('');
let allKnown=new Set(rebateData.programs.flatMap(p=>p.models.map(x=>x.model)));let unknown=[...new Set(models.filter(m=>!allKnown.has(m)))];let ub=$('unknownBox');if(unknown.length){ub.classList.remove('hidden');ub.innerHTML=`<strong>Not found in any active rebate:</strong><br>${unknown.join(', ')}`}else ub.classList.add('hidden');
if(!models.length){$('detailBody').innerHTML='<tr><td colspan="5" class="empty">Enter models to begin.</td></tr>';return}
$('detailBody').innerHTML=models.map((m,i)=>{let cells=rebateData.programs.map(p=>{let r=results[p.id],x=r.matches[i];if(!x)return '<td><span class="pill no">Not listed</span></td>';let counted=r.counts[i];let msg=p.id==='commercial'&&r.amount===0?'Listed; pair incomplete':counted?'Eligible / counted':'Eligible / count limited';return `<td><span class="pill ${counted?'yes':'limited'}">${msg}</span><span class="sub">${x.category}</span></td>`});return `<tr><td class="model">${m}</td>${cells.join('')}</tr>`}).join('')}
